---
- become: 'yes'
  become_method: sudo
  become_user: root
  hosts: zerow
  tasks:
    - apt:
        name: xserver-xorg
    - apt:
        name: xinit
    - apt:
        name: x11-xserver-utils
    - apt:
        name: chromium-browser
    - apt:
        name: matchbox-window-manager
    - apt:
        name: xautomation
    - apt:
        name: unclutter
    - apt:
        name: fonts-noto-color-emoji
